# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-31 00:50
from __future__ import unicode_literals

from django.db import migrations, models
import myutil


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ch11',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('gender', models.CharField(max_length=1)),
                ('dob', models.DateField(blank=True, null=True)),
                ('epaper', models.BooleanField(default=False)),
            ],
            bases=(models.Model, myutil.MyModel),
        ),
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.CharField(max_length=30)),
                ('lastname', models.CharField(max_length=30)),
                ('age', models.IntegerField(blank=True, null=True)),
            ],
        ),
    ]
