# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'contactEdit.ui'
#
# Created by: PySide2 UI code generator 5.4.2
#
# WARNING! All changes made in this file will be lost!

from PySide2 import QtCore, QtGui, QtWidgets

class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(426, 515)
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(Form)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setObjectName("gridLayout")
        self.label = QtWidgets.QLabel(Form)
        self.label.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 0, 0, 1, 1)
        self.id = QtWidgets.QLineEdit(Form)
        self.id.setObjectName("id")
        self.gridLayout.addWidget(self.id, 0, 1, 1, 1)
        self.label_3 = QtWidgets.QLabel(Form)
        self.label_3.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_3.setObjectName("label_3")
        self.gridLayout.addWidget(self.label_3, 0, 2, 1, 1)
        self.yonghu = QtWidgets.QLineEdit(Form)
        self.yonghu.setObjectName("yonghu")
        self.gridLayout.addWidget(self.yonghu, 0, 3, 1, 1)
        self.label_2 = QtWidgets.QLabel(Form)
        self.label_2.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_2.setObjectName("label_2")
        self.gridLayout.addWidget(self.label_2, 1, 0, 1, 1)
        self.addr = QtWidgets.QLineEdit(Form)
        self.addr.setObjectName("addr")
        self.gridLayout.addWidget(self.addr, 1, 1, 1, 1)
        self.label_4 = QtWidgets.QLabel(Form)
        self.label_4.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_4.setObjectName("label_4")
        self.gridLayout.addWidget(self.label_4, 1, 2, 1, 1)
        self.channels = QtWidgets.QLineEdit(Form)
        self.channels.setObjectName("channels")
        self.gridLayout.addWidget(self.channels, 1, 3, 1, 1)
        self.label_5 = QtWidgets.QLabel(Form)
        self.label_5.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_5.setObjectName("label_5")
        self.gridLayout.addWidget(self.label_5, 2, 0, 1, 1)
        self.yiqixinghao = QtWidgets.QLineEdit(Form)
        self.yiqixinghao.setObjectName("yiqixinghao")
        self.gridLayout.addWidget(self.yiqixinghao, 2, 1, 1, 1)
        self.label_12 = QtWidgets.QLabel(Form)
        self.label_12.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_12.setObjectName("label_12")
        self.gridLayout.addWidget(self.label_12, 2, 2, 1, 1)
        self.yiqibh = QtWidgets.QLineEdit(Form)
        self.yiqibh.setObjectName("yiqibh")
        self.gridLayout.addWidget(self.yiqibh, 2, 3, 1, 1)
        self.label_6 = QtWidgets.QLabel(Form)
        self.label_6.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_6.setObjectName("label_6")
        self.gridLayout.addWidget(self.label_6, 3, 0, 1, 1)
        self.baoxiang = QtWidgets.QLineEdit(Form)
        self.baoxiang.setObjectName("baoxiang")
        self.gridLayout.addWidget(self.baoxiang, 3, 1, 1, 1)
        self.label_9 = QtWidgets.QLabel(Form)
        self.label_9.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_9.setObjectName("label_9")
        self.gridLayout.addWidget(self.label_9, 3, 2, 1, 1)
        self.shenhe = QtWidgets.QLineEdit(Form)
        self.shenhe.setObjectName("shenhe")
        self.gridLayout.addWidget(self.shenhe, 3, 3, 1, 1)
        self.label_7 = QtWidgets.QLabel(Form)
        self.label_7.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_7.setObjectName("label_7")
        self.gridLayout.addWidget(self.label_7, 4, 0, 1, 1)
        self.label_11 = QtWidgets.QLabel(Form)
        self.label_11.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_11.setObjectName("label_11")
        self.gridLayout.addWidget(self.label_11, 4, 2, 1, 1)
        self.label_8 = QtWidgets.QLabel(Form)
        self.label_8.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_8.setObjectName("label_8")
        self.gridLayout.addWidget(self.label_8, 5, 0, 1, 1)
        self.hetongbh = QtWidgets.QLineEdit(Form)
        self.hetongbh.setObjectName("hetongbh")
        self.gridLayout.addWidget(self.hetongbh, 5, 1, 1, 1)
        self.label_10 = QtWidgets.QLabel(Form)
        self.label_10.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_10.setObjectName("label_10")
        self.gridLayout.addWidget(self.label_10, 5, 2, 1, 1)
        self.method = QtWidgets.QLineEdit(Form)
        self.method.setObjectName("method")
        self.gridLayout.addWidget(self.method, 5, 3, 1, 1)
        self.yujifahuo_date = QtWidgets.QDateEdit(Form)
        self.yujifahuo_date.setObjectName("yujifahuo_date")
        self.gridLayout.addWidget(self.yujifahuo_date, 4, 1, 1, 1)
        self.tiaoshi_date = QtWidgets.QDateEdit(Form)
        self.tiaoshi_date.setObjectName("tiaoshi_date")
        self.gridLayout.addWidget(self.tiaoshi_date, 4, 3, 1, 1)
        self.verticalLayout_2.addLayout(self.gridLayout)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.pushButton = QtWidgets.QPushButton(Form)
        self.pushButton.setObjectName("pushButton")
        self.horizontalLayout.addWidget(self.pushButton)
        self.pushButton_2 = QtWidgets.QPushButton(Form)
        self.pushButton_2.setObjectName("pushButton_2")
        self.horizontalLayout.addWidget(self.pushButton_2)
        self.pushButton_3 = QtWidgets.QPushButton(Form)
        self.pushButton_3.setObjectName("pushButton_3")
        self.horizontalLayout.addWidget(self.pushButton_3)
        self.verticalLayout_2.addLayout(self.horizontalLayout)
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.table_usepacks = QtWidgets.QTableView(Form)
        self.table_usepacks.setObjectName("table_usepacks")
        self.verticalLayout.addWidget(self.table_usepacks)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.auto_usepack = QtWidgets.QComboBox(Form)
        self.auto_usepack.setCursor(QtGui.QCursor(QtCore.Qt.CrossCursor))
        self.auto_usepack.setStyleSheet("border-color: rgb(79, 82, 255);")
        self.auto_usepack.setEditable(True)
        self.auto_usepack.setMaxCount(2147483646)
        self.auto_usepack.setObjectName("auto_usepack")
        self.horizontalLayout_3.addWidget(self.auto_usepack)
        self.bibei = QtWidgets.QPushButton(Form)
        self.bibei.setStyleSheet("border-color: rgb(66, 66, 255);")
        self.bibei.setObjectName("bibei")
        self.horizontalLayout_3.addWidget(self.bibei)
        self.verticalLayout.addLayout(self.horizontalLayout_3)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.label_13 = QtWidgets.QLabel(Form)
        self.label_13.setObjectName("label_13")
        self.horizontalLayout_2.addWidget(self.label_13)
        self.newpack = QtWidgets.QLineEdit(Form)
        self.newpack.setObjectName("newpack")
        self.horizontalLayout_2.addWidget(self.newpack)
        self.pushButton_newpack = QtWidgets.QPushButton(Form)
        self.pushButton_newpack.setObjectName("pushButton_newpack")
        self.horizontalLayout_2.addWidget(self.pushButton_newpack)
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        self.verticalLayout_2.addLayout(self.verticalLayout)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.label.setText(_translate("Form", "ID"))
        self.label_3.setText(_translate("Form", "用户单位："))
        self.label_2.setText(_translate("Form", "客户地址:"))
        self.label_4.setText(_translate("Form", "通道配置:"))
        self.label_5.setText(_translate("Form", "仪器型号:"))
        self.label_12.setText(_translate("Form", "仪器编号:    "))
        self.label_6.setText(_translate("Form", "包箱:"))
        self.label_9.setText(_translate("Form", "    审核:"))
        self.label_7.setText(_translate("Form", "预计发货时间:"))
        self.label_11.setText(_translate("Form", "调试时间:"))
        self.label_8.setText(_translate("Form", "合同编号:"))
        self.label_10.setText(_translate("Form", "方法:"))
        self.yujifahuo_date.setDisplayFormat(_translate("Form", "yyyy-M-d"))
        self.tiaoshi_date.setDisplayFormat(_translate("Form", "yyyy-M-d"))
        self.pushButton.setText(_translate("Form", "保存"))
        self.pushButton_2.setText(_translate("Form", "清除"))
        self.pushButton_3.setText(_translate("Form", "复制"))
        self.bibei.setText(_translate("Form", "必备"))
        self.label_13.setText(_translate("Form", "新包名称："))
        self.pushButton_newpack.setText(_translate("Form", "新包"))

